SET DEFINE OFF;
DROP TABLE PDM_LOG.PROCESS_LOG CASCADE CONSTRAINTS;

CREATE TABLE PDM_LOG.PROCESS_LOG
(
  LOG_TIMESTAMP  TIMESTAMP(6),
  EVENT_ID       NUMBER,
  OWN_NAME       VARCHAR2(36 CHAR),
  PKG_NAME       VARCHAR2(36 CHAR),
  PROC_NAME      VARCHAR2(36 CHAR),
  LINE_NBR       NUMBER,
  USER_NAME      VARCHAR2(100 CHAR),
  TABLE_NAME     VARCHAR2(73 CHAR),
  NUM_RECS       NUMBER,
  COMMENTS       VARCHAR2(4000 CHAR),
  ERROR_TEXT     VARCHAR2(4000 CHAR)
)
TABLESPACE PDM_LOG
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE SYNONYM PDM_STG.PROCESS_LOG FOR PDM_LOG.PROCESS_LOG;


CREATE OR REPLACE PUBLIC SYNONYM PROCESS_LOG FOR PDM_LOG.PROCESS_LOG;


GRANT INSERT, SELECT ON PDM_LOG.PROCESS_LOG TO PDM_RPT;

GRANT INSERT, SELECT ON PDM_LOG.PROCESS_LOG TO PDM_STG;
