SET DEFINE OFF;
ALTER TABLE PDM_LOG.TIMING_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE PDM_LOG.TIMING_LOG CASCADE CONSTRAINTS;

CREATE TABLE PDM_LOG.TIMING_LOG
(
  JOB_ID         NUMBER,
  JOB_GROUP      VARCHAR2(75 BYTE),
  JOB_NAME       VARCHAR2(75 BYTE),
  PKG_NAME       VARCHAR2(36 BYTE),
  PROC_NAME      VARCHAR2(36 BYTE),
  JOB_STARTTIME  DATE,
  JOB_ENDTIME    DATE,
  STATUS         VARCHAR2(7 BYTE),
  SESSION_ID     NUMBER
);

CREATE OR REPLACE PUBLIC SYNONYM TIMING_LOG FOR PDM_LOG.TIMING_LOG;

ALTER TABLE PDM_LOG.TIMING_LOG ADD (
  PRIMARY KEY
  (JOB_ID)
  USING INDEX;
